spring:
  application:
    name: simplebanking
  messages:
    basename: messages
    encoding: UTF-8
    fallback-to-system-locale: false
    default-locale: en
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:simplebanking}
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  h2:
    console:
      enabled: false
  cache:
    type: simple

server:
  port: ${SERVER_PORT:8080}

logging:
  level:
    root: INFO
    com.eteration.simplebanking: DEBUG
    org.springframework.web: DEBUG
    org.springframework.transaction: DEBUG
    org.springframework.cache: DEBUG

app:
  security:
    algorithm: ${SECURITY_ALGORITHM}
    secret-key: ${SECURITY_SECRET_KEY}