version: '3.8'

services:
  postgres:
    image: postgres:13
    container_name: simplebanking-dev-postgres
    env_file:
      - ../docker/env.list
    ports:
      - "5432:5432"
    volumes:
      - postgres_dev_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_dev_data:

networks:
  default:
    name: simplebanking-dev-network 